version: '3'

services:

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data


  grafana:
    image: grafana/grafana-enterprise:8.2.0
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

volumes:
  db:
    driver: local